# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='default', upload_to=''),
        ),
    ]
